'use client'

import { createContext, useContext, useState, ReactNode } from 'react'

type Language = 'en' | 'zh'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// 翻译字典类型
type TranslationKeys = {
  [key: string]: string | string[]
}

// 翻译字典
const translations: Record<Language, TranslationKeys> = {
  en: {
    // Header
    'header.cases': 'Cases',
    'header.features': 'Features',
    'header.tokenomics': 'Tokenomics',
    'header.roadmap': 'Roadmap',
    'header.community': 'Community',
    'header.connectWallet': 'Connect Wallet',
    
    // Hero
    'hero.title': 'REVEAL PLATFORM',
    'hero.subtitle': 'Decentralized Web3 Whistleblowing Platform',
    'hero.description': 'Exposing misconduct by cryptocurrency exchanges, institutions and KOLs through anonymous reporting, community verification and governance token mechanisms, promoting transparency and fairness in the Web3 ecosystem. Becoming the most trusted decentralized whistleblowing platform.',
    'hero.anonymousProtection': 'Anonymous Protection',
    'hero.anonymousDesc': 'Zero-knowledge proof technology protects whistleblower identity',
    'hero.communityVerification': 'Community Verification',
    'hero.communityDesc': 'Decentralized verification mechanism ensures information authenticity',
    'hero.instantRewards': 'Instant Rewards',
    'hero.rewardsDesc': 'RCT token incentive mechanism rewards contributors',
    'hero.startReporting': 'Start Reporting',
    'hero.learnMore': 'Learn More',
    'hero.totalSupply': 'RCT Total Supply',
    'hero.communityAirdrop': 'Community Airdrop',
    'hero.governancePool': 'Governance Incentive Pool',
    'hero.transparency': 'Transparency Pursuit',
    
    // Cases
    'cases.title': 'Whistleblowing Cases',
    'cases.subtitle': 'Exposing misconduct in the Web3 ecosystem, promoting industry transparency and fairness',
    'cases.exchangeCategory': 'Exchange Sector',
    'cases.institutionCategory': 'Institution Sector',
    'cases.kolCategory': 'KOL Sector',
    'cases.mexcTitle': 'MEXC: Tony (Wang Yiyu) from Taoyuan Sankeng Relapses Again',
    'cases.mexcDesc': 'Recently, Tony (Wang Yiyu), the boss of MEXC platform from Taoyuan Sankeng, has relapsed again, starting to freeze Chinese users\' accounts on a large scale. Some users have had their account funds frozen ranging from 150K USDT to 500K USDT. Most of these users made profits through contracts, but after their accounts were frozen, they sought unfreezing channels everywhere, yet received no response through either official or private channels. This reminds people of Tony\'s previous behavior of opening Phoenix Entertainment Casino and freezing user funds, which are strikingly similar. PS: MEXC\'s actual controller Tony\'s real name is #Wang Yiyu. Criminal case filed in Chongqing, main culprit has been a fugitive for 15 years.',
    'cases.okxTitle': 'OKX: Why Doesn\'t Xu Mingxing Turn the Compliance Knife on Himself First?',
    'cases.okxDesc': 'To ensure the platform meets regulatory requirements, Xu Mingxing set strict compliance terms requiring users to provide up to 15 years of asset flow proof. If users cannot provide such proof, the platform will freeze their assets. While this helps meet compliance requirements, this policy has caused widespread user dissatisfaction, believing such regulations are too harsh and unreasonably affect their rights. Therefore, although Xu Mingxing\'s compliance strategy seems reasonable legally, it sacrifices the interests of broad users, creating tension between the platform and users.',
    'cases.gateTitle': 'Gate: Why Should Project Parties Bear the Pressure of Han Lin\'s Harem?',
    'cases.gateDesc': 'Gate.io\'s current predicament is not only reflected in the company\'s internal financial and management issues, but also involves improper trading behaviors between it and project parties. Han Lin and Jiu Er respectively control the company\'s key private keys and accounts, while the company\'s financial problems have led to generally low employee salaries, with the GateLabs department being particularly severe. This series of internal problems has intensified the power struggle between Han Lin and Jiu Er, also bringing enormous pressure from external project parties to the company.',
    'cases.institutionTitle': 'A Well-known Investment Institution Token Price Manipulation Case',
    'cases.institutionDesc': 'Using insider information and market manipulation methods to influence token price trends',
    'cases.kolTitle': 'Famous KOL Charges for Market Calls Without Disclosing Interest Relationships',
    'cases.kolDesc': 'Analyzing how some KOLs mislead retail investors by concealing interest relationships',
    'cases.complianceIssue': 'Compliance Issue',
    'cases.conflictOfInterest': 'Conflict of Interest',
    'cases.regulatoryEvasion': 'Regulatory Evasion',
    'cases.managementIssue': 'Management Issue',
    'cases.businessEthics': 'Business Ethics',
    'cases.projectImpact': 'Project Impact',
    'cases.marketManipulation': 'Market Manipulation',
    'cases.insiderTrading': 'Insider Trading',
    'cases.priceManipulation': 'Price Manipulation',
    'cases.disclosure': 'Interest Disclosure',
    'cases.misleadingInvestment': 'Misleading Investment',
    'cases.moralHazard': 'Moral Hazard',
    'cases.verified': 'Verified',
    'cases.verifying': 'Verifying',
    'cases.investigating': 'Investigating',
    'cases.high': 'High Risk',
    'cases.medium': 'Medium Risk',
    'cases.low': 'Low Risk',
    'cases.viewDetails': 'View Details',
    'cases.reportMore': 'Report More',
    'cases.viewMore': 'View More Cases',
    'cases.reportMisconduct': 'Found Misconduct? Report Now',
    'cases.reportDescription': 'Your report will be protected by anonymity, and you can earn RCT token rewards after community verification. Let\'s maintain the justice and transparency of the Web3 ecosystem together.',
    'cases.submitReport': 'Submit Anonymous Report',
    
    // Features
    'features.title': 'Core Platform Features',
    'features.subtitle': 'Building the safest, most transparent, and fair Web3 whistleblowing platform through advanced blockchain technology and governance mechanisms',
    'features.anonymousSubmission': 'Anonymous Submission System',
    'features.anonymousDesc': 'Using zero-knowledge proof and ring signature technology to completely protect whistleblower identity, with content stored on IPFS for censorship resistance',
    'features.communityVerification': 'Community Verification Mechanism',
    'features.verificationDesc': 'Community members stake RCT tokens to participate in verification, earning rewards for correct verification and bearing losses for incorrect verification, ensuring information authenticity',
    'features.decentralizedGovernance': 'Decentralized Governance',
    'features.governanceDesc': 'DAO governance model where RCT holders participate in voting through staking to decide platform rules, fund allocation, and development direction',
    'features.educationCenter': 'Education Resource Center',
    'features.educationDesc': 'Providing professional guides to teach users safe reporting, Web3 tool usage, legal risk awareness, and improving overall security awareness',
    'features.completeProtection': 'Complete Anonymous Protection',
    'features.privacyEncryption': 'Privacy Technology Encryption',
    'features.ipfsStorage': 'IPFS Decentralized Storage',
    'features.censorshipResistant': 'Censorship Resistant',
    'features.decentralizedVerification': 'Decentralized Verification',
    'features.stakingMechanism': 'Staking Mechanism Guarantee',
    'features.rewardIncentive': 'Reward Incentive System',
    'features.reputationSystem': 'Reputation System Assessment',
    'features.daoOrganization': 'DAO Autonomous Organization',
    'features.democraticVoting': 'Democratic Voting Decisions',
    'features.transparentFunding': 'Transparent Fund Management',
    'features.communityDriven': 'Community Driven Development',
    'features.safetyGuide': 'Safe Reporting Guide',
    'features.web3Tools': 'Web3 Tool Teaching',
    'features.legalWarning': 'Legal Risk Warning',
    'features.knowledgeSharing': 'Community Knowledge Sharing',
    'features.realTimeMonitoring': 'Real-time Monitoring',
    'features.monitoringDesc': '24/7 monitoring of Web3 ecosystem dynamics',
    'features.dataSecurity': 'Data Security',
    'features.securityDesc': 'End-to-end encryption protects all data',
    'features.rapidResponse': 'Rapid Response',
    'features.responseDesc': 'Emergency incident rapid processing mechanism',
    'features.globalCoverage': 'Global Coverage',
    'features.coverageDesc': 'Covering major Web3 platforms globally',
    'features.learnMore': 'Learn More',
    'features.techArchitecture': 'Technical Architecture',
    'features.techDesc': 'Built on the latest blockchain technology and cryptography',
    'features.blockchainFoundation': 'Blockchain Foundation',
    'features.privacyProtection': 'Privacy Protection',
    'features.governanceMechanism': 'Governance Mechanism',
    'features.solanaNetwork': 'Solana High-performance Network',
    'features.smartContracts': 'Smart Contract Auto-execution',
    'features.ipfsDecentralized': 'IPFS Decentralized Storage',
    'features.arweave': 'Arweave Permanent Storage',
    'features.zkProof': 'Zero-knowledge Proof Technology',
    'features.ringSignature': 'Ring Signature Anonymous Scheme',
    'features.e2eEncryption': 'End-to-end Encrypted Communication',
    'features.metadataProtection': 'Metadata Protection Mechanism',
    'features.proposalVoting': 'Proposal Voting System',
    'features.stakingRewards': 'Staking Reward Mechanism',
    'features.reputationAlgorithm': 'Reputation Assessment Algorithm',
    
    // Tokenomics
    'tokenomics.title': 'Token Economic Model',
    'tokenomics.subtitle': 'RCT (Reveal Coin Token) - Total supply of 10 billion, driving platform ecosystem development',
    'tokenomics.distribution': 'Token Distribution',
    'tokenomics.utilities': 'Token Utilities',
    'tokenomics.communityAirdrop': 'Community Airdrop',
    'tokenomics.airdropDesc': 'Rewarding whistleblowers and verifiers',
    'tokenomics.publicSale': 'Public Sale',
    'tokenomics.publicDesc': 'For community users',
    'tokenomics.governancePool': 'Governance Incentive Pool',
    'tokenomics.poolDesc': 'Supporting governance voting and incentives',
    'tokenomics.privateSale': 'Private Sale',
    'tokenomics.privateDesc': 'Early investors',
    'tokenomics.teamAdvisors': 'Team & Advisors',
    'tokenomics.teamDesc': '3-year gradual unlocking',
    'tokenomics.platformReserve': 'Platform Reserve',
    'tokenomics.reserveDesc': 'Operations and promotion',
    'tokenomics.governanceRights': 'Governance Rights',
    'tokenomics.governanceDesc': 'Stake RCT to participate in platform governance voting',
    'tokenomics.rewardEarning': 'Reward Earning',
    'tokenomics.rewardDesc': 'Verify reports to earn RCT token rewards',
    'tokenomics.premiumFeatures': 'Premium Features',
    'tokenomics.premiumDesc': 'Unlock exclusive content and fast verification',
    'tokenomics.revenueSharing': 'Revenue Sharing',
    'tokenomics.revenueDesc': 'Platform revenue used for RCT buyback and burn',
    'tokenomics.deflationMechanism': 'Deflation Mechanism',
    'tokenomics.revenueBuyback': 'Revenue Buyback',
    'tokenomics.buybackDesc': 'Platform advertising and donation revenue used for market RCT buyback',
    'tokenomics.tokenBurn': 'Token Burn',
    'tokenomics.burnDesc': 'Bought back RCT will be permanently burned, reducing total supply',
    'tokenomics.valueIncrease': 'Value Increase',
    'tokenomics.valueDesc': 'Drive continuous RCT value growth through supply reduction',
    'tokenomics.amount10M': '1B RCT',
    'tokenomics.amount20M': '2B RCT', 
    'tokenomics.amount30M': '3B RCT',
    
    // Roadmap
    'roadmap.title': 'Development Roadmap',
    'roadmap.subtitle': 'From concept to implementation, building Web3\'s most trusted whistleblowing platform',
    'roadmap.q1Title': '2025 Q1',
    'roadmap.q1Items': 'Complete platform concept design and publish whitepaper\nStart backend infrastructure development\nBuild core team and advisory team\nEstablish smart contract framework',
    'roadmap.q2Title': '2025 Q2',
    'roadmap.q2Items': 'Develop Alpha version for internal testing\nDesign and implement RCT smart contract\nLaunch community building and marketing activities\nAttract early users for testing',
    'roadmap.q3Title': '2025 Q3',
    'roadmap.q3Items': 'Release Beta version for public testing\nConduct RCT token generation event\nLaunch community airdrop program\nIntegrate IPFS decentralized storage',
    'roadmap.q4Title': '2025 Q4',
    'roadmap.q4Items': 'Official mainnet launch\nHold RCT public sale\nActivate governance functions\nCommunity begins participating in decisions',
    'roadmap.active': 'In Progress',
    'roadmap.upcoming': 'Coming Soon',
    'roadmap.futureTitle': '2026 and Beyond',
    'roadmap.continuousIteration': 'Continuous Iteration',
    'roadmap.iterationDesc': 'Continuously optimize platform features based on community feedback',
    'roadmap.ecosystemExpansion': 'Ecosystem Expansion',
    'roadmap.expansionDesc': 'Establish partnerships with media and transparency organizations',
    'roadmap.globalImpact': 'Global Impact',
    'roadmap.impactDesc': 'Become the most authoritative oversight platform in the Web3 ecosystem',
    
    // Community
    'community.title': 'Join Our Community',
    'community.subtitle': 'Together with global Web3 transparency advocates, building a fair and open digital ecosystem',
    'community.followers': 'Followers',
    'community.joinNow': 'Join Now',
    'community.activities': 'Community Activities',
    'community.rewards': 'Contribution Rewards',
    'community.ama': 'AMA Q&A',
    'community.amaDesc': 'Regular team Q&A sessions, direct dialogue with developers',
    'community.onlineSalon': 'Online Salon',
    'community.salonDesc': 'Discuss Web3 transparency topics and industry trends',
    'community.airdropActivity': 'Airdrop Activities',
    'community.airdropDesc': 'Participate in testing and contributions to earn RCT token rewards',
    'community.governanceVoting': 'Governance Voting',
    'community.votingDesc': 'Community members participate in important platform decisions',
    'community.weekly': 'Weekly',
    'community.monthly': 'Monthly',
    'community.ongoing': 'Ongoing',
    'community.asNeeded': 'As Needed',
    'community.submitReport': 'Submit Valid Report',
    'community.verifyReport': 'Verify Report Authenticity',
    'community.participateGovernance': 'Participate in Governance Voting',
    'community.promoteplatform': 'Promote Platform',
    'community.reportDesc': 'Based on report importance and impact',
    'community.verifyDesc': 'Earn rewards for correct verification',
    'community.governanceDesc': 'Actively participate in community governance',
    'community.promoteDesc': 'Effective promotion earns referral rewards',
    'community.startParticipating': 'Start Participating Now',
    'community.participateDesc': 'Whether you\'re a Web3 enthusiast, investor, or developer, you\'re welcome to join our mission. Let\'s build a more transparent and fair digital world together.',
    'community.joinTelegram': 'Join Telegram Group',
    'community.followTwitter': 'Follow Twitter Updates',
    
    // Footer
    'footer.about': 'About Us',
    'footer.aboutUs': 'About Us',
    'footer.howToReport': 'How to Report',
    'footer.verificationProcess': 'Verification Process',
    'footer.governanceMechanism': 'Governance Mechanism',
    'footer.twitter': 'Twitter',
    'footer.telegram': 'Telegram',
    'footer.discord': 'Discord',
    'footer.forum': 'Forum',
    'footer.whitepaper': 'Whitepaper',
    'footer.technicalDocs': 'Technical Documentation',
    'footer.securityGuide': 'Security Guide',
    'footer.faq': 'FAQ',
    'footer.termsOfService': 'Terms of Service',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.disclaimer': 'Disclaimer',
    'footer.contactUs': 'Contact Us',
    'footer.description': 'Decentralized Web3 whistleblowing platform dedicated to promoting transparency and fairness in the cryptocurrency industry. Through anonymous protection, community verification, and DAO governance, becoming the most trusted oversight platform in the Web3 ecosystem.',
    'footer.poweredBy': 'Powered by Solana',
    'footer.builtWith': 'Built with ❤️ for Web3 transparency',
    'footer.builtWithLove': 'Built with ❤️ for Web3 transparency',
    'footer.securityNotice': 'Security Notice',
    'footer.securityWarning': 'Security Warning',
    'footer.securityDesc': 'Reveal Platform will never ask for your private keys or seed phrases. Please be aware of phishing websites and scams. All official links are based on this website and official social media.',
    'footer.platform': 'Platform',
    'footer.community': 'Community',
    'footer.resources': 'Resources',
    'footer.legal': 'Legal',
    'footer.website': 'Official Website',
    'footer.visiting': 'Visiting',
    
    // Metadata
    'meta.title': 'Reveal Platform - Decentralized Web3 Whistleblowing Platform',
    'meta.description': 'Exposing misconduct by cryptocurrency exchanges, institutions and KOLs, promoting Web3 ecosystem transparency',
    'meta.keywords': ['Web3', 'Whistleblowing', 'Decentralized', 'Blockchain', 'DeFi', 'Cryptocurrency'],
    wallet: {
      loading: 'Loading...',
      addressCopied: 'Address copied!',
      connected: 'Connected',
      address: 'Wallet Address',
      balance: 'SOL Balance',
      fetchingBalance: 'Fetching balance...',
      network: 'Network',
      viewOnSolscan: 'View on Solscan',
      disconnect: 'Disconnect'
    },
    caseDetails: {
      description: 'Case Description',
      timeline: 'Event Timeline',
      evidence: 'Evidence Materials',
      impact: 'Impact Assessment',
      recommendation: 'Recommendations',
      tags: 'Related Tags',
      viewSource: 'View Source',
      reportUpdate: 'Report Updates',
      downloadReport: 'Download Report',
      viewDetailedReport: 'View Detailed Report',
      sourceDocuments: 'Source Documents',
      okx: {
        timeline1: 'January 2024 - Whistleblower first reported OKX executives abusing power for personal gain',
        timeline2: 'February 2024 - Community verification team began investigating evidence, discovering internal interest transfer issues',
        timeline3: 'March 2024 - More internal documents and decision records involving compliance double standards were discovered',
        timeline4: 'April 2024 - Case entered public review stage, awaiting final regulatory decision',
        evidence1: 'Internal OKX emails show executives had private business relationships with specific project parties, violating internal controls',
        evidence2: 'Trading records prove insider trading behavior, affecting market fairness and user rights',
        evidence3: 'Multiple employees anonymously reported management violations and conflicts of interest, providing detailed evidence',
        evidence4: 'Regulatory documents show OKX has compliance issues and double standards in multiple jurisdictions',
        evidence5: 'Feishu internal documents recorded Xu Mingxing\'s decision-making process and internal discussions on compliance issues',
        impact: 'This case seriously damaged user trust in centralized exchanges and exposed governance defects within the industry. The impact involves asset security and trading fairness for millions of users, causing negative effects on the reputation of the entire cryptocurrency ecosystem. Particularly regarding compliance double standards, it had important implications for industry regulatory policy formulation.',
        recommendation: 'It is recommended that regulatory authorities strengthen supervision of exchange internal governance and require exchanges to establish more comprehensive internal control mechanisms. Users should raise risk awareness, diversify asset storage, and avoid concentrating all funds on a single platform. It is also recommended to establish industry transparency standards to prevent compliance double standard issues.',
        sourceLink: 'https://suspezlb1df1.sg.larksuite.com/wiki/DSBQwyBzXiJOhJksBoRlaFKvgod',
        sourceName: 'OKX Compliance Issues Detailed Investigation Report - Feishu Document'
      },
      gate: {
        timeline1: 'January 2024 - Gate.io exchange exposed for major flaws in project review process',
        timeline2: 'February 2024 - Multiple fake projects passed review and went live, causing over $10 million in user losses',
        timeline3: 'March 2024 - Internal employees reported management accepting bribes from project parties with detailed evidence',
        timeline4: 'April 2024 - Platform began internal reforms but refused to admit systemic issues and responsibility',
        evidence1: 'Fake technical documents and team information provided by projects passed platform review',
        evidence2: 'Internal chat records show financial transactions between reviewers and project parties',
        evidence3: 'User loss statistics show problem projects caused over $10 million in losses',
        evidence4: 'Employee whistleblower letters revealed management misconduct and decision processes',
        impact: 'This case exposed serious flaws in second-tier exchanges\' project review processes, affecting investor confidence in new projects. The direct economic losses and reputational damage had negative impacts on the entire DeFi ecosystem.',
        recommendation: 'Industry-wide unified project review standards should be established, with increased participation from third-party audit institutions. Exchanges should implement stricter internal control systems to prevent internal corruption and conflicts of interest.'
      },
      default: {
        timeline1: 'Case first reported, preliminary investigation began',
        timeline2: 'Collected more related evidence and witness testimonies',
        timeline3: 'Case entered public review and community discussion phase',
        evidence1: 'Related transaction records and fund flow evidence',
        evidence2: 'Public statements and internal communication records of parties involved',
        evidence3: 'Investigation reports and analyses from third-party institutions',
        impact: 'This case has had important impacts on related industries and user groups, requiring continued attention and supervision.',
        recommendation: 'Relevant parties should strengthen compliance awareness, improve internal control mechanisms, and protect user rights.'
      }
    }
  },
  zh: {
    // Header
    'header.cases': '爆料案例',
    'header.features': '平台功能',
    'header.tokenomics': '代币经济',
    'header.roadmap': '发展路线',
    'header.community': '社区',
    'header.connectWallet': '连接钱包',
    
    // Hero
    'hero.title': 'REVEAL PLATFORM',
    'hero.subtitle': '去中心化Web3爆料平台',
    'hero.description': '曝光加密货币交易所、机构和KOL的不当行为，通过匿名投料、社区验证和治理代币机制，推动Web3生态的透明度和公正性。成为最可信赖的去中心化爆料平台。',
    'hero.anonymousProtection': '匿名保护',
    'hero.anonymousDesc': '零知识证明技术保护爆料者身份',
    'hero.communityVerification': '社区验证',
    'hero.communityDesc': '去中心化验证机制确保信息真实性',
    'hero.instantRewards': '即时奖励',
    'hero.rewardsDesc': 'RCT代币激励机制奖励贡献者',
    'hero.startReporting': '开始爆料',
    'hero.learnMore': '了解更多',
    'hero.totalSupply': 'RCT总供应量',
    'hero.communityAirdrop': '社区空投',
    'hero.governancePool': '治理激励池',
    'hero.transparency': '透明度追求',
    
    // Cases
    'cases.title': '爆料案例',
    'cases.subtitle': '揭露Web3生态中的不当行为，推动行业透明度和公正性',
    'cases.exchangeCategory': '交易所板块',
    'cases.institutionCategory': '机构板块',
    'cases.kolCategory': 'KOL板块',
    'cases.mexcTitle': '抹茶：桃园三坑的抹茶平台老板Tony（王奕宇）再次旧病复发',
    'cases.mexcDesc': '最近，桃园三坑的抹茶平台老板Tony（王奕宇）再次旧病复发，开始大规模冻结中国用户的账户。部分用户的账户资金被冻结金额从15W USDT到50W USDT不等。这些用户大多数都是通过合约盈利，但在账户被冻结后，他们四处寻求解冻途径，然而无论是通过官方渠道还是私人申请，都未得到任何回应。令人不禁联想到Tony曾开设凤凰娱乐赌场并冻结用户资金的行为，二者如出一辙。PS:MEXC 实控人 Tony 真名 #王奕宇    重庆刑事立案，主犯潜逃 15 年',
    'cases.okxTitle': 'OKX：徐明星合规之路为何第一选择不向自己挥刀？',
    'cases.okxDesc': '为了确保平台符合监管要求，徐明星设置了严格的合规条款，要求用户提供高达15年的资产流水证明。如果用户未能提供该证明，平台将冻结其资产。尽管此举有助于满足合规要求，但这一政策引发了大量用户的不满，认为这种规定过于苛刻，且不合理地影响了他们的权益。\n\n因此，徐明星的合规策略虽然在法律层面上看似有理，但却牺牲了广泛用户的利益，造成了平台与用户之间的紧张关系。这种做法实际上是将合规成本转嫁给了用户，而不是通过完善内部管理和技术手段来解决合规问题。\n\n更为关键的是，这种政策的执行标准存在明显的双重标准，对不同用户群体采用不同的执行尺度，缺乏公平性和透明度。',
    'cases.gateTitle': 'Gate：Gate韩林圈养后宫的压力为何要项目方承担？',
    'cases.gateDesc': 'Gate.io当前的困境不仅体现在公司内部的财务和管理问题上，还涉及到其与项目方之间的不正当交易行为。韩林和酒儿分别掌控着公司的关键私钥和账号，而公司的财务问题则让员工的薪资普遍较低，GateLabs部门尤为严重。这一系列内部问题加剧了韩林与酒儿之间的权力斗争，也给公司带来了外部项目方的巨大压力。\n\n在这种情况下，韩林与酒儿的权力博弈让项目方承受了额外的压力。项目方不仅要面对平台不稳定的风险，还得应对Gate.io的"数据砸盘"行为。多个项目方反映，平台上标的的市值账户被冻结，充值和提现权限被关闭。某个控盘达98%的标的即使价格已经跌至极低，仍然持续砸盘，导致项目方几乎无法回收投资。\n\n要想重新开启权限，项目方必须投入数十万美元，通过MM账号拉升币价，才能恢复基本操作权限。这种情况暴露出Gate.io在管理和财务方面的混乱，而项目方却成了背负"后宫压力"的受害者。',
    'cases.institutionTitle': '某知名投资机构操纵代币价格案例',
    'cases.institutionDesc': '通过内幕信息和市场操控手段影响代币价格走势',
    'cases.kolTitle': '知名KOL收费喊单却不披露利益关系',
    'cases.kolDesc': '分析某些KOL如何通过隐瞒利益关系误导散户投资者',
    'cases.complianceIssue': '合规问题',
    'cases.conflictOfInterest': '利益冲突',
    'cases.regulatoryEvasion': '监管逃避',
    'cases.managementIssue': '管理问题',
    'cases.businessEthics': '商业道德',
    'cases.projectImpact': '项目影响',
    'cases.marketManipulation': '市场操控',
    'cases.insiderTrading': '内幕交易',
    'cases.priceManipulation': '价格操纵',
    'cases.disclosure': '利益披露',
    'cases.misleadingInvestment': '误导投资',
    'cases.moralHazard': '道德风险',
    'cases.verified': '已验证',
    'cases.verifying': '验证中',
    'cases.investigating': '调查中',
    'cases.high': '高危',
    'cases.medium': '中危',
    'cases.low': '低危',
    'cases.viewDetails': '查看详情',
    'cases.reportMore': '举报补充',
    'cases.viewMore': '查看更多案例',
    'cases.reportMisconduct': '发现不当行为？立即举报',
    'cases.reportDescription': '您的举报将受到匿名保护，经社区验证后可获得RCT代币奖励。让我们一起维护Web3生态的公正与透明。',
    'cases.submitReport': '匿名提交爆料',
    
    // Features
    'features.title': '平台核心功能',
    'features.subtitle': '通过先进的区块链技术和治理机制，打造最安全、透明、公正的Web3爆料平台',
    'features.anonymousSubmission': '匿名投料系统',
    'features.anonymousDesc': '采用零知识证明和环签名技术，完全保护爆料者身份，内容存储在IPFS确保不可审查',
    'features.communityVerification': '社区验证机制',
    'features.verificationDesc': '社区成员质押RCT代币参与验证，正确验证获得奖励，错误验证承担损失，确保信息真实性',
    'features.decentralizedGovernance': '去中心化治理',
    'features.governanceDesc': 'DAO治理模式，RCT持有者通过质押参与投票，决定平台规则、资金分配和发展方向',
    'features.educationCenter': '教育资源中心',
    'features.educationDesc': '提供专业指南教用户安全爆料、使用Web3工具、了解法律风险，提升整体安全意识',
    'features.completeProtection': '完全匿名保护',
    'features.privacyEncryption': '隐私技术加密',
    'features.ipfsStorage': 'IPFS去中心化存储',
    'features.censorshipResistant': '不可审查特性',
    'features.decentralizedVerification': '去中心化验证',
    'features.stakingMechanism': '质押机制保障',
    'features.rewardIncentive': '奖励激励制度',
    'features.reputationSystem': '声誉系统评估',
    'features.daoOrganization': 'DAO自治组织',
    'features.democraticVoting': '民主投票决策',
    'features.transparentFunding': '透明资金管理',
    'features.communityDriven': '社区驱动发展',
    'features.safetyGuide': '安全爆料指南',
    'features.web3Tools': 'Web3工具教学',
    'features.legalWarning': '法律风险提醒',
    'features.knowledgeSharing': '社区知识共享',
    'features.realTimeMonitoring': '实时监控',
    'features.monitoringDesc': '24/7监控Web3生态动态',
    'features.dataSecurity': '数据安全',
    'features.securityDesc': '端到端加密保护所有数据',
    'features.rapidResponse': '快速响应',
    'features.responseDesc': '紧急事件快速处理机制',
    'features.globalCoverage': '全球覆盖',
    'features.coverageDesc': '覆盖全球主要Web3平台',
    'features.learnMore': '了解详情',
    'features.techArchitecture': '技术架构',
    'features.techDesc': '基于最新的区块链技术和密码学构建',
    'features.blockchainFoundation': '区块链基础',
    'features.privacyProtection': '隐私保护',
    'features.governanceMechanism': '治理机制',
    'features.solanaNetwork': 'Solana高性能网络',
    'features.smartContracts': '智能合约自动执行',
    'features.ipfsDecentralized': 'IPFS去中心化存储',
    'features.arweave': 'Arweave永久存储',
    'features.zkProof': '零知识证明技术',
    'features.ringSignature': '环签名匿名方案',
    'features.e2eEncryption': '端到端加密通信',
    'features.metadataProtection': '元数据保护机制',
    'features.proposalVoting': '提案投票系统',
    'features.stakingRewards': '质押奖惩机制',
    'features.reputationAlgorithm': '声誉评估算法',
    
    // Tokenomics
    'tokenomics.title': '代币经济模型',
    'tokenomics.subtitle': 'RCT（Reveal Coin Token）- 总供应量100亿，推动平台生态发展',
    'tokenomics.distribution': '代币分配',
    'tokenomics.utilities': '代币用途',
    'tokenomics.communityAirdrop': '社区空投',
    'tokenomics.airdropDesc': '奖励爆料者和验证者',
    'tokenomics.publicSale': '公开售卖',
    'tokenomics.publicDesc': '面向社区用户',
    'tokenomics.governancePool': '治理激励池',
    'tokenomics.poolDesc': '支持治理投票和激励',
    'tokenomics.privateSale': '私人售卖',
    'tokenomics.privateDesc': '早期投资者',
    'tokenomics.teamAdvisors': '团队顾问',
    'tokenomics.teamDesc': '3年逐步解锁',
    'tokenomics.platformReserve': '平台储备',
    'tokenomics.reserveDesc': '运营和推广',
    'tokenomics.governanceRights': '治理权益',
    'tokenomics.governanceDesc': '质押RCT参与平台治理投票',
    'tokenomics.rewardEarning': '奖励获取',
    'tokenomics.rewardDesc': '验证爆料获得RCT代币奖励',
    'tokenomics.premiumFeatures': '高级功能',
    'tokenomics.premiumDesc': '解锁独家内容和快速验证',
    'tokenomics.revenueSharing': '收益分配',
    'tokenomics.revenueDesc': '平台收入用于回购销毁RCT',
    'tokenomics.deflationMechanism': '通缩机制',
    'tokenomics.revenueBuyback': '收入回购',
    'tokenomics.buybackDesc': '平台广告、捐款收入用于市场回购RCT',
    'tokenomics.tokenBurn': '代币销毁',
    'tokenomics.burnDesc': '回购的RCT将被永久销毁，减少总供应量',
    'tokenomics.valueIncrease': '价值提升',
    'tokenomics.valueDesc': '通过供应量减少推动RCT价值持续增长',
    'tokenomics.amount10M': '1B RCT',
    'tokenomics.amount20M': '2B RCT', 
    'tokenomics.amount30M': '3B RCT',
    
    // Roadmap
    'roadmap.title': '发展路线图',
    'roadmap.subtitle': '从概念到实现，构建Web3最可信赖的爆料平台',
    'roadmap.q1Title': '2025 Q1',
    'roadmap.q1Items': '完成平台概念设计，发布白皮书\n开始后端基础设施开发\n组建核心团队和顾问团队\n搭建智能合约框架',
    'roadmap.q2Title': '2025 Q2',
    'roadmap.q2Items': '开发Alpha版本，内部测试\n设计并实现RCT智能合约\n启动社区建设和营销活动\n吸引早期用户参与测试',
    'roadmap.q3Title': '2025 Q3',
    'roadmap.q3Items': '发布Beta版本，公开测试\n进行RCT代币生成事件\n启动社区空投计划\n整合IPFS去中心化存储',
    'roadmap.q4Title': '2025 Q4',
    'roadmap.q4Items': '主网正式上线\n举行RCT公开售卖\n激活治理功能\n社区开始参与决策',
    'roadmap.active': '进行中',
    'roadmap.upcoming': '即将开始',
    'roadmap.futureTitle': '2026年及以后',
    'roadmap.continuousIteration': '持续迭代',
    'roadmap.iterationDesc': '根据社区反馈不断优化平台功能',
    'roadmap.ecosystemExpansion': '生态扩展',
    'roadmap.expansionDesc': '与媒体和透明度组织建立合作',
    'roadmap.globalImpact': '全球影响',
    'roadmap.impactDesc': '成为Web3生态最权威的监督平台',
    
    // Community
    'community.title': '加入我们的社区',
    'community.subtitle': '与全球Web3透明度倡导者一起，共建公正公开的数字生态',
    'community.followers': '关注者',
    'community.joinNow': '立即加入',
    'community.activities': '社区活动',
    'community.rewards': '贡献奖励',
    'community.ama': 'AMA问答',
    'community.amaDesc': '定期举办团队问答，直接对话开发者',
    'community.onlineSalon': '在线沙龙',
    'community.salonDesc': '讨论Web3透明度话题和行业动态',
    'community.airdropActivity': '空投活动',
    'community.airdropDesc': '参与测试和贡献获得RCT代币奖励',
    'community.governanceVoting': '治理投票',
    'community.votingDesc': '社区成员参与平台重要决策',
    'community.weekly': '每周三',
    'community.monthly': '每月',
    'community.ongoing': '持续进行',
    'community.asNeeded': '按需举行',
    'community.submitReport': '提交有效爆料',
    'community.verifyReport': '验证爆料真实性',
    'community.participateGovernance': '参与治理投票',
    'community.promoteplatform': '推广平台',
    'community.reportDesc': '根据爆料重要性和影响力',
    'community.verifyDesc': '正确验证获得奖励',
    'community.governanceDesc': '积极参与社区治理',
    'community.promoteDesc': '有效推广获得推荐奖励',
    'community.startParticipating': '立即开始参与',
    'community.participateDesc': '无论您是Web3爱好者、投资者还是开发者，都欢迎加入我们的使命。一起构建更透明、更公正的数字世界。',
    'community.joinTelegram': '加入Telegram群组',
    'community.followTwitter': '关注Twitter动态',
    
    // Footer
    'footer.about': '关于我们',
    'footer.aboutUs': '关于我们',
    'footer.howToReport': '如何爆料',
    'footer.verificationProcess': '验证流程',
    'footer.governanceMechanism': '治理机制',
    'footer.twitter': 'Twitter',
    'footer.telegram': 'Telegram',
    'footer.discord': 'Discord',
    'footer.forum': '论坛',
    'footer.whitepaper': '白皮书',
    'footer.technicalDocs': '技术文档',
    'footer.securityGuide': '安全指南',
    'footer.faq': 'FAQ',
    'footer.termsOfService': '服务条款',
    'footer.privacyPolicy': '隐私政策',
    'footer.disclaimer': '免责声明',
    'footer.contactUs': '联系我们',
    'footer.description': '去中心化Web3爆料平台，致力于推动加密货币行业的透明度和公正性。通过匿名保护、社区验证和DAO治理，成为Web3生态最可信赖的监督平台。',
    'footer.poweredBy': 'Powered by Solana',
    'footer.builtWith': 'Built with ❤️ for Web3 transparency',
    'footer.builtWithLove': 'Built with ❤️ for Web3 transparency',
    'footer.securityNotice': '安全提示',
    'footer.securityWarning': '安全提示',
    'footer.securityDesc': 'Reveal Platform永远不会要求您提供私钥或助记词。请注意防范钓鱼网站和诈骗。所有官方链接请以本网站和官方社交媒体为准。',
    'footer.platform': '平台',
    'footer.community': '社区',
    'footer.resources': '资源',
    'footer.legal': '法律',
    'footer.website': '官方网站',
    'footer.visiting': '访问中',
    
    // Metadata
    'meta.title': 'Reveal Platform - 去中心化Web3爆料平台',
    'meta.description': '专注于曝光加密货币交易所、机构和KOL的不当行为，推动Web3生态透明度',
    'meta.keywords': ['Web3', '爆料', '去中心化', '区块链', 'DeFi', '加密货币'],
    wallet: {
      loading: '加载中...',
      addressCopied: '地址已复制!',
      connected: '已连接',
      address: '钱包地址',
      balance: 'SOL余额',
      fetchingBalance: '获取余额中...',
      network: '网络',
      viewOnSolscan: '在Solscan查看',
      disconnect: '断开连接'
    },
    caseDetails: {
      description: '案例描述',
      timeline: '事件时间线',
      evidence: '证据材料',
      impact: '影响评估',
      recommendation: '建议措施',
      tags: '相关标签',
      viewSource: '查看原始资料',
      reportUpdate: '举报更新信息',
      downloadReport: '下载报告',
      viewDetailedReport: '查看详细报告',
      sourceDocuments: '原始文档',
      okx: {
        timeline1: '2024年1月 - 爆料人首次举报OKX高管利用职权谋取私利',
        timeline2: '2024年2月 - 社区验证团队开始调查相关证据，发现内部利益输送问题',
        timeline3: '2024年3月 - 发现更多涉及合规双重标准的内部文件和决策记录',
        timeline4: '2024年4月 - 案例进入公开审核阶段，等待监管机构最终裁决',
        evidence1: 'OKX内部邮件显示高管与特定项目方存在私下利益往来，违反内控制度',
        evidence2: '交易记录证明存在内幕交易行为，影响市场公平性和用户权益',
        evidence3: '多位员工匿名举报管理层违规操作和利益冲突，提供详细证据',
        evidence4: '监管文件显示OKX在多个司法管辖区存在合规问题和双重标准',
        evidence5: '飞书内部文档记录了徐明星在合规问题上的决策过程和内部讨论',
        impact: '该案例严重损害了用户对中心化交易所的信任，暴露了行业内部治理的缺陷。影响范围涉及数百万用户的资产安全和交易公平性，对整个加密货币生态系统的声誉造成负面影响。特别是在合规双重标准方面，对行业监管政策制定产生了重要影响。',
        recommendation: '建议监管机构加强对交易所内部治理的监督，要求交易所建立更完善的内控机制。用户应提高风险意识，分散资产存储，避免将所有资金集中在单一平台。同时建议建立行业透明度标准，防止合规双重标准问题。',
        sourceLink: 'https://suspezlb1df1.sg.larksuite.com/wiki/DSBQwyBzXiJOhJksBoRlaFKvgod',
        sourceName: 'OKX合规问题详细调查报告 - 飞书文档'
      },
      gate: {
        timeline1: '2024年1月 - 芝麻开门交易所被曝出项目审核流程存在重大漏洞',
        timeline2: '2024年2月 - 多个虚假项目通过审核上线，导致用户损失超过千万美元',
        timeline3: '2024年3月 - 内部员工举报管理层收受项目方贿赂，提供详细证据',
        timeline4: '2024年4月 - 平台开始内部整改，但拒绝承认系统性问题和责任',
        evidence1: '项目方提供的虚假技术文档和团队信息通过了平台审核',
        evidence2: '内部聊天记录显示审核人员与项目方存在资金往来',
        evidence3: '多位用户损失统计显示问题项目造成超过1000万美元损失',
        evidence4: '员工举报信揭露了管理层的不当行为和决策过程',
        impact: '此案例暴露了二线交易所在项目审核方面的严重缺陷，影响了投资者对新项目的信心。造成的直接经济损失和声誉损害对整个DeFi生态系统产生了负面冲击。',
        recommendation: '建议建立行业统一的项目审核标准，加强第三方审计机构的参与。交易所应实施更严格的内控制度，防止内部腐败和利益冲突。'
      },
      default: {
        timeline1: '案例首次被举报，开始初步调查',
        timeline2: '收集到更多相关证据和证人证言',
        timeline3: '案例进入公开审核和社区讨论阶段',
        evidence1: '相关的交易记录和资金流向证据',
        evidence2: '当事人的公开声明和内部通讯记录',
        evidence3: '第三方机构的调查报告和分析',
        impact: '该案例对相关行业和用户群体产生了重要影响，需要持续关注和监督。',
        recommendation: '相关各方应加强合规意识，完善内控机制，保护用户权益。'
      }
    }
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en') // 默认英文

  const t = (key: string): string => {
    const translation = translations[language][key]
    if (Array.isArray(translation)) {
      // 对于keywords使用逗号分隔，其他用换行符
      if (key === 'meta.keywords') {
        return translation.join(', ')
      }
      return translation.join('\n')
    }
    return translation || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
} 